Repository highVTest/E-Commerce, pull requests merged in 2024-07, with the labels that each got.

#9 Feat item-cart crud
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/Oauth/Controller/KakaoOAuthLoginController.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/Service/KakaoOAuthLoginService.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/client/KakaoOAuthLoginClient.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/client/config/RestClientConfig.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/client/dto/KakaoLoginUserInfoResponse.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/client/dto/KakaoTokenResponse.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/client/dto/KakaoUserPropertiesResponse.kt
  src/main/kotlin/com/highv/ecommerce/common/dto/AccessTokenResponse.kt
  src/main/kotlin/com/highv/ecommerce/common/exception/LoginException.kt
  src/main/kotlin/com/highv/ecommerce/common/exception/dto/ErrorResponse.kt
  src/main/kotlin/com/highv/ecommerce/common/exception/handler/GlobalExceptionHandler.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/controller/BuyerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/BuyerResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/CreateBuyerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/entity/Buyer.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/repository/BuyerRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/controller/ItemCartController.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/dto/request/SelectProductQuantity.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/dto/response/ItemCartResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/entity/ItemCart.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/repository/ItemCartRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/service/ItemCartService.kt
  src/main/kotlin/com/highv/ecommerce/domain/login/controller/UserController.kt
  src/main/kotlin/com/highv/ecommerce/domain/login/dto/LoginRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/login/service/UserService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/controller/SellerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/dto/CreateSellerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/dto/SellerResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/entity/Seller.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/repository/SellerRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/service/SellerService.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/CustomAccessDeniedHandler.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/PasswordEncoderConfig.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/SecurityConfig.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/UserPrincipal.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/jwt/JwtPlugin.kt
  src/main/kotlin/com/highv/ecommerce/infra/swagger/SwaggerConfig.kt
  src/main/kotlin/com/highv/ecommerce/socialmember/entity/KakaoSocialMember.kt
  src/main/kotlin/com/highv/ecommerce/socialmember/service/SocialMemberDomainService.kt
  src/test/kotlin/com/highv/ecommerce/item_cart/ItemCartEntityTest.kt
  src/test/kotlin/com/highv/ecommerce/item_cart/ItemCartServiceTest.kt
Labels: ✨Feat, 🐛Fix, ♻Refactor, ✅Test

#11 Feat Implement favorite feature
  src/main/kotlin/com/highv/ecommerce/domain/favorite/controller/FavoriteController.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/entity/Favorite.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/repository/FavoriteRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/SecurityConfig.kt
  src/test/kotlin/com/highv/ecommerce/favorite/FavoriteServiceTest.kt
Labels: ✨Feat, ✅Test

#18 Feat/#3 impl seller backoffice
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/InventoryManagementController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SalesStatisticsController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SellerInfoController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/productbackoffice/ProductBackOfficeResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/salesstatics/ProductSalesQuantityResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/salesstatics/ProductSalesResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/salesstatics/TotalSalesQuantityResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/salesstatics/TotalSalesResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdatePasswordRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdateSellerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdateShopRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/entity/ProductBackOffice.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/entity/SalesHistory.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/repository/ProductBackOfficeRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/InventoryManagementService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesStatisticsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SellerInfoService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/category/controller/CategoryController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/category/dto/CategoryResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/category/entity/Category.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/category/repository/CategoryRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/category/service/CategoryService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/CreateProductRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/ProductResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/UpdateProductRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/entity/Product.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/entity/Seller.kt
  src/main/kotlin/com/highv/ecommerce/domain/shop/controller/ShopController.kt
  src/main/kotlin/com/highv/ecommerce/domain/shop/dto/CreateShopRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/shop/dto/ShopResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/shop/entity/Shop.kt
  src/main/kotlin/com/highv/ecommerce/domain/shop/repository/ShopRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/shop/service/ShopService.kt
  src/main/kotlin/com/highv/ecommerce/infra/queryDSL/QueryDslConfig.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/SecurityConfig.kt
  src/test/kotlin/com/highv/ecommerce/ProductServiceTest.kt
Labels: ✨Feat, 🐛Fix, ♻Refactor

#23 Feat/#14 profile revision
  src/main/kotlin/com/highv/ecommerce/domain/buyer/controller/BuyerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/CreateBuyerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/UpdateBuyerImageRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/UpdateBuyerPasswordRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/UpdateBuyerProfileRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/response/BuyerResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/entity/Buyer.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/test/kotlin/com/highv/ecommerce/buyer/BuyerServiceTest.kt
Labels: ✨Feat, ✅Test

#24 Feat/#1 Implement login test code
  src/test/kotlin/com/highv/ecommerce/item_cart/ItemCartServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/loginBuyerServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/loginSellerServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/loginUserServiceTest.kt
Labels: ✅Test

#28 Feat/#27 refactor seller backoffice
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/repository/ProductBackOfficeRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/InventoryManagementService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesStatisticsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/category/controller/CategoryController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/entity/Product.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/shop/repository/ShopRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/shop/service/ShopService.kt
Labels: ♻Refactor

#17 Feat/#16 impl oauth naver
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/Oauth/Controller/KakaoOAuthLoginController.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/Controller/OAuthLoginController.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/OAuthClient.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/OAuthClientService.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/OAuthLoginService.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/Service/KakaoOAuthLoginService.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/client/config/WebConfig.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/converter/OAuthProviderConverter.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/kakao/KakaoOAuthLoginClient.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/kakao/dto/KakaoLoginUserInfoResponse.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/kakao/dto/KakaoTokenResponse.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/kakao/dto/KakaoUserPropertiesResponse.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/naver/NaverOAuthLoginClient.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/naver/dto/NaverLoginUserInfoResponse.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/naver/dto/NaverResponse.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/naver/dto/NaverTokenResponse.kt
  src/main/kotlin/com/highv/ecommerce/Oauth/naver/dto/OAuthLoginUserInfo.kt
  src/main/kotlin/com/highv/ecommerce/common/type/OAuthProvider.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/entity/Buyer.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/repository/BuyerRepository.kt
  src/main/kotlin/com/highv/ecommerce/socialmember/entity/SocialMember.kt
  src/main/kotlin/com/highv/ecommerce/socialmember/service/SocialMemberDomainService.kt
Labels: ✨Feat, 🐛Fix, ♻Refactor

#21 Feat/#7 Paymemt Domain And Order Status Domain
  .gitignore
  src/main/kotlin/com/highv/ecommerce/common/dto/DefaultResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/repository/SalesHistoryRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesStatisticsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/entity/Buyer.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer_history/entity/BuyerHistory.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer_history/repository/BuyerHistoryRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/entity/ItemCart.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/repository/ItemCartRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/service/ItemCartService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/controller/OrderStatusController.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/dto/BuyerOrderStatusRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/dto/OrderStatusResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/dto/SellerOrderStatusRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/entity/OrderStatus.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/enumClass/RejectReason.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/repository/OrderStatusJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/repository/OrderStatusRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/repository/OrderStatusRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/service/OrderStatusService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/ProductResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/entity/Product.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/controller/ProductsOrderController.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/dto/OrderStatusRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/dto/ProductsOrderResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/entity/ProductsOrder.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/enumClass/OrderStatusType.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/enumClass/StatusCode.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/repository/ProductsOrderRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/service/ProductsOrderService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/entity/Seller.kt
  src/test/kotlin/com/highv/ecommerce/item_cart/ItemCartEntityTest.kt
Labels: ✨Feat, 🐛Fix, ♻Refactor

#15 Feat/#4 coupon domain crud
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/common/aop/annotation_class/RedissonLock.kt
  src/main/kotlin/com/highv/ecommerce/common/aop/aspect/RedissonLockAspect.kt
  src/main/kotlin/com/highv/ecommerce/common/dto/DefaultResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/controller/CouponController.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/controller/CouponControllerVn.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/dto/CouponResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/dto/CreateCouponRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/dto/UpdateCouponRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/entity/Coupon.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/entity/CouponToBuyer.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/enumClass/DiscountPolicy.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/service/CouponService.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/service/CouponServiceVn.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/infra/redisson/RedissonConfig.kt
  src/test/kotlin/com/highv/ecommerce/ProductServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/coupon/method/dto/CreateCouponRequestTest.kt
  src/test/kotlin/com/highv/ecommerce/coupon/method/entity/CouponTest.kt
  src/test/kotlin/com/highv/ecommerce/coupon/service/CouponServiceTest.kt
Labels: ✨Feat, ✅Test

#36 Feat/#19 impl sales history
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SalesHistoryController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/saleshistory/SalesHistoryResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/repository/SalesHistoryRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesHistoryService.kt
Labels: ✨Feat

#37 Feat/#34 apply coupon logic
  src/main/kotlin/com/highv/ecommerce/domain/coupon/controller/CouponController.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/service/CouponService.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/entity/ItemCart.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_status/controller/OrderStatusController.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/controller/ProductsOrderController.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/dto/CouponRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/entity/TotalPriceDto.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/repository/ProductsOrderJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/repository/ProductsOrderRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/repository/ProductsOrderRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/products_order/service/ProductsOrderService.kt
  src/test/kotlin/com/highv/ecommerce/coupon/service/CouponServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/favorite/FavoriteServiceTest.kt
Labels: ✨Feat

#44 Refactor/#43 optimization payment and order
  src/main/kotlin/com/highv/ecommerce/domain/order_details/controller/OrderDetailsController.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/OrderStatusResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/SellerOrderStatusRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/entity/OrderDetails.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/enumClass/OrderStatus.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/controller/OrderMasterController.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
Labels: ♻Refactor

#47 Feat/#25 implement s3 image upload
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/Oauth/naver/NaverOAuthLoginClient.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/controller/BuyerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/controller/SellerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/service/SellerService.kt
  src/main/kotlin/com/highv/ecommerce/s3/config/FileUtil.kt
  src/main/kotlin/com/highv/ecommerce/s3/config/s3Manager.kt
  src/main/kotlin/com/highv/ecommerce/s3/config/s3config.kt
Labels: ✨Feat, 🐛Fix

#48 Feat/#45 apply coupon
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/entity/Coupon.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/entity/CouponToBuyer.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/service/CouponService.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/entity/ItemCart.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/repository/ItemCartRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/service/ItemCartService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/controller/OrderDetailsController.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/BuyerOrderStatusRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/entity/OrderDetails.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/controller/OrderMasterController.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/dto/CouponRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/dto/PaymentRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/dto/ProductsOrderResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/dto/TotalPriceDto.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/repository/OrderMasterRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/repository/OrderMasterRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
Labels: ✨Feat, 🐛Fix, ♻Refactor

#51 feat/#40 - Search Redis
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/productbackoffice/ProductBackOfficeRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/repository/FavoriteRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductSearchController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/ProductResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/TopSearchKeyword.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/entity/Product.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/QueryDslExtentions.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductSearchService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/infra/redis/RedisConfig.kt
Labels: ✨Feat

#53 Feat/#41 Implement Admin Backoffice
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/admin/controller/AdminController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/admin/dto/BlackListResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/admin/dto/CreateBlackListRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/admin/entity/BlackList.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/admin/repository/BlackListRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/admin/service/AdminService.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/entity/Seller.kt
  src/main/kotlin/com/highv/ecommerce/infra/security/SecurityConfig.kt
Labels: ✨Feat, ♻Refactor

#54 Refactor/#46 buyer logic
  src/main/kotlin/com/highv/ecommerce/domain/auth/controller/UserController.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/dto/EmailAuthRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/dto/EmailAuthResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/service/UserService.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/controller/BuyerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/CreateBuyerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/response/BuyerHistoryProductResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/response/BuyerOrderResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/controller/FavoriteController.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/dto/FavoriteResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/repository/FavoriteRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/controller/ItemCartController.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/dto/response/CartResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/dto/response/ItemCartResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/dto/response/ItemResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/entity/ItemCart.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/service/ItemCartService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/controller/OrderDetailsController.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/BuyerOrderDetailProductResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/BuyerOrderResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/BuyerOrderShopResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/entity/OrderDetails.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/repository/OrderMasterJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/repository/OrderMasterRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/repository/OrderMasterRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/controller/SellerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/dto/CreateSellerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/service/SellerService.kt
Labels: 🐛Fix, ♻Refactor

#62 Test/#50 test oreder and coupon
  src/main/kotlin/com/highv/ecommerce/domain/order_details/entity/OrderDetails.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
  src/test/kotlin/com/highv/ecommerce/coupon/method/entity/CouponTest.kt
  src/test/kotlin/com/highv/ecommerce/coupon/service/CouponServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/order_detail/method/OrderDetailMethodTest.kt
  src/test/kotlin/com/highv/ecommerce/order_detail/service/OrderDetailsServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/order_master/service/OrderMasterServiceService.kt
Labels: ✅Test

#64 Feat/#58 Implement Admin Backoffice Test Code
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/admin/service/AdminService.kt
  src/test/kotlin/com/highv/ecommerce/backoffice/AdminBackOfficeServiceTest.kt
Labels: ✅Test

#65 Feat/#55 impl product review
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ReviewController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/CreateReviewRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/ReviewResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/UpdateReviewRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/entity/Review.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ReviewRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ReviewService.kt
  src/test/kotlin/com/highv/ecommerce/OAuth/SocialMemberDomainServiceTest.kt
Labels: ✨Feat, ♻Refactor

#76 Feat/#68 impl rate system
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SalesHistoryController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/saleshistory/SalesHistoryResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesHistoryService.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/dto/ReviewRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/dto/UpdateReviewRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/service/ReviewService.kt
Labels: ✨Feat

#79 Feat/#68 impl rate system
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SellerInfoService.kt
  src/test/kotlin/com/highv/ecommerce/admin/AdminBackOfficeServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/backoffice/InventoryManagementServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/backoffice/SalesStatisticsServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/backoffice/SellerInfoServiceTest.kt
Labels: ✅Test

#80 Feat/#73 impl error handling
  src/main/kotlin/com/highv/ecommerce/common/exception/CustomRuntimeException.kt
  src/main/kotlin/com/highv/ecommerce/common/exception/handler/GlobalExceptionHandler.kt
  src/main/kotlin/com/highv/ecommerce/domain/admin/service/AdminService.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/controller/UserController.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/oauth/kakao/KakaoOAuthLoginClient.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/oauth/naver/NaverOAuthLoginClient.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/service/UserService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SellerInfoService.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/controller/BuyerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/controller/CouponController.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/controller/CouponControllerVn.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/entity/Coupon.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/service/CouponService.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/service/CouponServiceVn.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/entity/ItemCart.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/service/ItemCartService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/OrderStatusResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/SellerOrderStatusRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/entity/OrderDetails.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/entity/Review.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/service/ReviewService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/service/SellerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/shop/service/ShopService.kt
  src/main/kotlin/com/highv/ecommerce/infra/email/EmailUtils.kt
  src/main/kotlin/com/highv/ecommerce/infra/s3/s3Manager.kt
  src/test/kotlin/com/highv/ecommerce/oauth/SocialMemberDomainServiceTest.kt
Labels: ♻Refactor

#84 Test/#83 product and review
  src/main/kotlin/com/highv/ecommerce/domain/review/service/ReviewService.kt
  src/test/kotlin/com/highv/ecommerce/category/CategoryServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/product/ProductServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/review/ReviewServiceTest.kt
Labels: ✅Test

#85 Feat/#66 implement oauth test
  src/main/kotlin/com/highv/ecommerce/domain/coupon/controller/CouponController.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/entity/Review.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/service/ReviewService.kt
  src/test/kotlin/com/highv/ecommerce/OAuth/SocialMemberDomainServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/admin/AdminBackOfficeServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesStatisticsServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/oauth/SocialMemberDomainServiceTest.kt
Labels: ✅Test

#92 Refactor/#89 shop and seller
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SellerInfoController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SellerInfoService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductSearchService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/controller/SellerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/service/SellerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/shop/controller/ShopController.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/shop/service/ShopService.kt
  src/test/kotlin/com/highv/ecommerce/backoffice/SalesStatisticsServiceTest.kt
Labels: ✨Feat, ♻Refactor, ✅Test
