Repository highVTest/E-Commerce, pull requests merged in 2024-08, with the labels that each got.

#104 Refactor/#103 product seller bo
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/InventoryManagementController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SalesStatisticsController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SellerInfoController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/productbackoffice/PriceRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/productbackoffice/QuantityRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/productbackoffice/SellersProductResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdateSellerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdateShopRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/InventoryManagementService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SellerInfoService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/CreateRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/entity/Product.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
Labels: ♻Refactor

#113 Refactor/#105 refactor seller codes
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/InventoryManagementController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SalesStatisticsController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SellerInfoController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/salesstatics/ProductSalesQuantityResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/salesstatics/ProductSalesResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/salesstatics/TotalSalesQuantityResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/salesstatics/TotalSalesResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdatePasswordRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/repository/ProductBackOfficeRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/InventoryManagementService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesStatisticsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SellerInfoService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/test/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesStatisticsServiceTest.kt
Labels: 🐛Fix, ♻Refactor

#115 Refactor/#106 buyer logic fix
  src/main/kotlin/com/highv/ecommerce/domain/buyer/controller/BuyerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/CreateBuyerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/controller/ItemCartController.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/dto/response/CartResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/entity/ItemCart.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/service/ItemCartService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/BuyerOrderShopResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/entity/OrderDetails.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
  src/main/kotlin/com/highv/ecommerce/infra/s3/FileUtil.kt
  src/main/resources/application.yml
  src/test/kotlin/com/highv/ecommerce/buyer/BuyerServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/favorite/FavoriteServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/item_cart/ItemCartEntityTest.kt
  src/test/kotlin/com/highv/ecommerce/item_cart/ItemCartServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/SignUpServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/order_detail/method/OrderDetailMethodTest.kt
  src/test/kotlin/com/highv/ecommerce/order_detail/service/BuyerOrderServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/order_detail/service/OrderDetailsServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/order_master/service/OrderMasterServiceService.kt
Labels: ♻Refactor, ✅Test

#116 refactor image upload
  src/main/kotlin/com/highv/ecommerce/common/image/controller/ImageController.kt
  src/main/kotlin/com/highv/ecommerce/common/image/dto/ImageUrlResponse.kt
  src/main/kotlin/com/highv/ecommerce/common/image/service/ImageService.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/controller/UserController.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/oauth/Controller/OAuthLoginController.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/service/UserService.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/highv/ecommerce/infra/s3/entity/Image.kt
  src/main/kotlin/com/highv/ecommerce/infra/s3/s3Manager.kt
  src/test/kotlin/com/highv/ecommerce/OAuth/SocialMemberDomainServiceTest.kt
Labels: ✨Feat, ♻Refactor

#125 Feat implement delivery status
  src/main/kotlin/com/highv/ecommerce/common/image/controller/ImageController.kt
  src/main/kotlin/com/highv/ecommerce/common/image/service/ImageService.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/CreateBuyerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/controller/OrderDetailsController.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/dto/UpdateDeliveryStatusRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/entity/OrderDetails.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/repository/OrderDetailsRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/service/SellerService.kt
  src/main/kotlin/com/highv/ecommerce/infra/s3/s3Manager.kt
Labels: ✨Feat, 🐛Fix, ♻Refactor

#108 Test Refactor
  src/test/kotlin/com/highv/ecommerce/admin/AdminBackOfficeServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/SignUpServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/loginUserServiceTest.kt
Labels: ♻Refactor, ✅Test

#123 Implement approveSellerResignation, promotePendingSe…
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/common/innercall/TxAdvice.kt
  src/main/kotlin/com/highv/ecommerce/domain/admin/controller/AdminController.kt
  src/main/kotlin/com/highv/ecommerce/domain/admin/service/AdminService.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/service/UserService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/dto/ActiveStatus.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/entity/Seller.kt
  src/test/kotlin/com/highv/ecommerce/admin/AdminBackOfficeServiceTest.kt
Labels: ✨Feat

#130 ✨feat: Implement Concurrency on OrderMasterService
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/common/lock/service/RedisLockService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/controller/OrderMasterController.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/dto/PaymentRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/CreateRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
Labels: ✨Feat

#132 몽고db 연결 완료
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/ECommerceApplication.kt
  src/main/kotlin/com/highv/ecommerce/common/image/controller/ImageController.kt
  src/main/kotlin/com/highv/ecommerce/common/image/dto/ImageRequest.kt
  src/main/kotlin/com/highv/ecommerce/common/image/entity/Image.kt
  src/main/kotlin/com/highv/ecommerce/common/image/repository/ImageRepository.kt
  src/main/kotlin/com/highv/ecommerce/common/image/service/ImageService.kt
  src/main/kotlin/com/highv/ecommerce/infra/mongodb/MongoConfig.kt
  src/main/kotlin/com/highv/ecommerce/infra/mongodb/MongoTemplateConfig.kt
  src/main/kotlin/com/highv/ecommerce/infra/mongodb/SearchMongoProperties.kt
  src/main/kotlin/com/highv/ecommerce/infra/s3/entity/Image.kt
  src/main/resources/application.yml
Labels: ✨Feat, 🐛Fix, ♻Refactor

#139 Feat/#138 front
  src/main/kotlin/com/highv/ecommerce/common/innercall/TxAdvice.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/service/UserService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SellerInfoController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/productbackoffice/SellersProductResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdateImageRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SellerInfoService.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/repository/FavoriteRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductSearchController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/CreateProductRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductSearchService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/controller/SellerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/dto/CreateSellerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/service/SellerService.kt
Labels: 🐛Fix, ♻Refactor

#140 Concurrency for Create Product
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
Labels: ✨Feat

#142 :bug: imageupload fix
  src/main/kotlin/com/highv/ecommerce/common/image/controller/ImageController.kt
  src/main/kotlin/com/highv/ecommerce/common/image/dto/ImageRequest.kt
  src/main/kotlin/com/highv/ecommerce/common/image/repository/ImageRepository.kt
  src/main/kotlin/com/highv/ecommerce/common/image/service/ImageService.kt
Labels: 🐛Fix, ♻Refactor

#147 :bug: fix OrderMasterService bug
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
  src/main/resources/application.yml
Labels: 🐛Fix

#144 Feat/#143 impl hysup readme
  src/README.md
Labels: ✨Feat

#141 :sparkles: Implement README.md
  src/README.md
Labels: ✨Feat

#150 :recycle: Refactor README.md File Location
  README.md
Labels: ♻Refactor

#155 Feat/#143 impl hysup readme
  README.md
Labels: ♻Refactor

#163 :bug: fix: Fix product update
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/InventoryManagementController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SellerInfoController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/productbackoffice/PriceRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/productbackoffice/QuantityRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdateSellerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/CreateProductRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/UpdateProductRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductSearchService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
Labels: 🐛Fix

#165 :bug: fixed payment Service
  src/main/kotlin/com/highv/ecommerce/domain/order_master/service/OrderMasterService.kt
Labels: 🐛Fix

#172 Feat/#152 impl image test (Remove MongoDB)
  build.gradle.kts
  src/main/kotlin/com/highv/ecommerce/common/image/controller/ImageController.kt
  src/main/kotlin/com/highv/ecommerce/common/image/dto/ImageRequest.kt
  src/main/kotlin/com/highv/ecommerce/common/image/entity/Image.kt
  src/main/kotlin/com/highv/ecommerce/common/image/repository/ImageRepository.kt
  src/main/kotlin/com/highv/ecommerce/common/image/service/ImageService.kt
  src/main/kotlin/com/highv/ecommerce/infra/mongodb/MongoConfig.kt
  src/main/kotlin/com/highv/ecommerce/infra/mongodb/MongoTemplateConfig.kt
  src/main/kotlin/com/highv/ecommerce/infra/mongodb/SearchMongoProperties.kt
  src/main/resources/application.yml
  src/test/kotlin/com/highv/ecommerce/Image/ImageServiceTest.kt
Labels: ♻Refactor

#177 Refactor/#176 Query Performance for search
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/controller/ProductSearchController.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/ProductSummaryDto.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/ProductSummaryResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductSearchService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/infra/redis/config/RedisConfig.kt
Labels: ♻Refactor

#175 Feat/#174 refactor review service
  src/main/kotlin/com/highv/ecommerce/common/image/service/ImageService.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/entity/Review.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/repository/ReviewQueryDslRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/service/ReviewService.kt
  src/test/kotlin/com/highv/ecommerce/Image/ImageServiceTest.kt
Labels: ♻Refactor

#169 Fix email and phoneNumver valid
  src/main/kotlin/com/highv/ecommerce/domain/auth/controller/UserController.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/dto/EmailAuthRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/dto/sellerInfo/UpdateSellerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/controller/BuyerController.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/CreateBuyerRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/dto/request/UpdateBuyerProfileRequest.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/dto/CreateSellerRequest.kt
Labels: 🐛Fix

#185 Feat/#180 impl admin login
  src/main/kotlin/com/highv/ecommerce/common/exception/AdminLoginFailedException.kt
  src/main/kotlin/com/highv/ecommerce/domain/admin/controller/AdminController.kt
  src/main/kotlin/com/highv/ecommerce/domain/admin/entity/Admin.kt
  src/main/kotlin/com/highv/ecommerce/domain/admin/repository/AdminRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/admin/service/AdminService.kt
Labels: ✨Feat

#183 Implement getSellerLists
  src/main/kotlin/com/highv/ecommerce/domain/admin/controller/AdminController.kt
  src/main/kotlin/com/highv/ecommerce/domain/admin/service/AdminService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/dto/SellerResponse.kt
Labels: ✨Feat

#184 Refactor/#179 Change review logic
  src/main/kotlin/com/highv/ecommerce/domain/review/repository/ReviewQueryDslRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/repository/ReviewQueryDslRepositoryImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/service/ReviewService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/repository/SellerRepository.kt
Labels: ✨Feat, ♻Refactor

#187 Refactor/#170 buyer query decrease
  src/main/kotlin/com/highv/ecommerce/domain/favorite/controller/FavoriteController.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/dto/FavoriteCount.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/repository/FavoriteQueryDsl.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/repository/FavoriteQueryDslImpl.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/repository/FavoriteRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/repository/ItemCartQueryDsl.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/repository/ItemCartRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/service/ItemCartService.kt
  src/main/kotlin/com/highv/ecommerce/domain/order_details/service/OrderDetailsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/ProductSummaryDto.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/dto/ProductSummaryResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductSearchService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
Labels: 🐛Fix, ♻Refactor

#192 Fix query logics
  src/main/kotlin/com/highv/ecommerce/domain/admin/service/AdminService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/InventoryManagementService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesStatisticsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SellerInfoService.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/repository/ProductRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/product/service/ProductService.kt
  src/main/kotlin/com/highv/ecommerce/domain/seller/shop/repository/ShopRepository.kt
Labels: 🐛Fix

#181 Implement README
  README.md
Labels: ♻Refactor

#204 remove comments
  src/main/kotlin/com/highv/ecommerce/domain/admin/controller/AdminController.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/controller/UserController.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/oauth/OAuthClientService.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/oauth/naver/dto/NaverResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/auth/service/UserService.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/controller/SalesStatisticsController.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/entity/ProductBackOffice.kt
  src/main/kotlin/com/highv/ecommerce/domain/backoffice/service/SalesStatisticsService.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/repository/BuyerRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/buyer/service/BuyerService.kt
  src/main/kotlin/com/highv/ecommerce/domain/coupon/repository/CouponToBuyerJpaRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/dto/FavoriteResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/repository/FavoriteRepository.kt
  src/main/kotlin/com/highv/ecommerce/domain/favorite/service/FavoriteService.kt
Labels: ♻Refactor

#208 :bug: fix: Fix buyer response and controller path-variable
  src/main/kotlin/com/highv/ecommerce/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/dto/BuyerReviewResponse.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/service/ReviewService.kt
  src/main/resources/application.yml
Labels: 🐛Fix, ♻Refactor

#211 Fix/#210 buyer logic testcode
  src/main/kotlin/com/highv/ecommerce/domain/item_cart/service/ItemCartService.kt
  src/main/kotlin/com/highv/ecommerce/domain/review/service/ReviewService.kt
  src/test/kotlin/com/highv/ecommerce/buyer/BuyerServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/favorite/FavoriteServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/item_cart/ItemCartEntityTest.kt
  src/test/kotlin/com/highv/ecommerce/item_cart/ItemCartServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/SignUpServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/loginBuyerServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/loginSellerServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/login/loginUserServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/order_detail/service/BuyerOrderServiceTest.kt
  src/test/kotlin/com/highv/ecommerce/review/ReviewServiceTest.kt
Labels: 🐛Fix, ♻Refactor, ✅Test

#213 Update README to final version
  README.md
Labels: ✨Feat, ♻Refactor
